spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springqs?characterEncoding=utf-8
    username: root
    password: mysqlroot
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: debug
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
security:
  basic:
    enabled: false
storage:
  uploadPath=file:./upload

wechat:
  mp:
    appId: wxb21b41f0c6415294
    secret: e86f3561a68ae8bc2ebccf2000c02a21
    token: scan
    aesKey:

---
spring:
  profiles: prodcreate
  datasource:
    url: jdbc:mysql://localhost:3306/springqs?characterEncoding=utf-8
    username: root
    password: godbosoftABC123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: debug
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
security:
  basic:
    enabled: false
storage:
  uploadPath=file:./upload

wechat:
  mp:
    appId: wxb21b41f0c6415294
    secret: e86f3561a68ae8bc2ebccf2000c02a21
    token: scan
    aesKey:
server:
  port: 9000

---
spring:
  profiles: produpdate
  datasource:
    url: jdbc:mysql://localhost:3306/springqs?characterEncoding=utf-8
    username: root
    password: godbosoftABC123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: warn
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
security:
  basic:
    enabled: false
storage:
  uploadPath=file:./upload

wechat:
  mp:
    appId: wxb21b41f0c6415294
    secret: e86f3561a68ae8bc2ebccf2000c02a21
    token: scan
    aesKey:
server:
  port: 9000